### ISSUE TITLE
UTF8 decode error when open unit-select page in prep-screen

### ISSUE THREAD

**Issue by MokhaLeee** [StanHash/fe6-wizardry#1]
![image](https://user-images.githubusercontent.com/89029102/218298099-cd07fac1-91d0-4990-9aa3-8ee0cd689542.png)

Seems some of JIS strings is not converted. But since I'm not quite familiar to those jis-2-utf8 code, So I'm not quite sure how to fix it.

**Comment by StanHash** [comment]
I will try to add these strings when I have more time, but for now when you find something like that you can also try to fix it yourself by doing this:

in wizardry/unicode/string-locations.txt, add this line:

    08327260 Identifier # Optionally you can add a translated string like so: "String"

and do `make -C wizardry/unicode` (requires python 3)

You can also look in the generated wizardry/unicode/data/fe6-strings.s for what the original japanese string is if you need to translate it.

Do this until you don't have issues anymore

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/FE6-SkillLite/commit/7fc44b41164eecb9331b06d276954df8d8efe253

made it!

**Comment by StanHash** [comment]
I have added your findings in 9fd320c
